title: Selectie
hero_image: images/banner.png
description: Hoe gebruik je als blokken voor selectie op de micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Als blokken gebruiken voor selectie op de micro:bit
