title: Επιλογή
hero_image: images/banner.png
description: Πώς να χρησιμοποιήσεις τα μπλοκ εάν για επιλογή στο micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Χρήση μπλοκ εάν για επιλογή στο micro:bit
