---
title: Sélection
hero_image: images/banner.png
description: Comment utiliser les blocs si pour la sélection sur le micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Utilise des blocs si pour la sélection sur le micro:bit
